CREATE TYPE "public"."invitation_issuer" AS ENUM('workspace', 'platform');--> statement-breakpoint
ALTER TABLE "messages" ADD COLUMN "sent_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspace_invitations" ADD COLUMN "issuer_scope" "invitation_issuer" DEFAULT 'workspace' NOT NULL;--> statement-breakpoint
-- Messages already out were sent when they were written, as far as anything recorded says.
-- Idempotent: only rows still without a time are touched.
UPDATE "messages" SET "sent_at" = "created_at"
WHERE "direction" = 'outbound' AND "status" IN ('sent', 'delivered', 'read') AND "sent_at" IS NULL;
--> statement-breakpoint
-- One membership per person per workspace. Duplicates, if a race ever made any, keep the
-- oldest row. Written here by hand rather than declared in schema/auth.ts, because that file
-- is regenerated by `bun run auth:generate` and would lose it.
DELETE FROM "member" m
USING "member" older
WHERE m."organization_id" = older."organization_id"
  AND m."user_id" = older."user_id"
  AND (older."created_at", older."id") < (m."created_at", m."id");
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "member_org_user_uq" ON "member" ("organization_id", "user_id");
